stages:
  - plan

variables:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"

terraform_plan:
  stage: plan
  image: hashicorp/terraform:1.0.9
  script:
    - cd .
    - terraform --version
    - terraform init
    - terraform validate
    - terraform plan
