stages:
  - terraform-plan
  - terraform-apply
  - terraform-destroy

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

terraform-plan:
  stage: terraform-plan
  image: hashicorp/terraform:latest
  script:
    - terraform init
    - terraform plan
  only:
    - master

terraform-apply:
  stage: terraform-apply
  image: hashicorp/terraform:latest
  script:
    - terraform apply -auto-approve

terraform-destroy:
  stage: terraform-destroy
  script:
    - terraform destroy -auto-approve
  when: manual
