# .gitlab-ci.yml
# file is working with a pre-defined template

include:
  - template: Terraform/Base.gitlab-ci.yml

variables:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"

stages:
  - validate
  - build
  - deploy
  - destroy

validate:
  extends: .terraform:validate

build:
  extends: .terraform:build

terraform_deploy:
  stage: deploy
  script:
    - gitlab-terraform apply -auto-approve

cleanup:
  stage: destroy
  script:
    - gitlab-terraform destroy -auto-approve
