stages:
  - plan
  - apply
  - destroy

variables:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"

terraform_plan:
  stage: plan
  script:
    - gitlab-terraform init
    - gitlab-terraform validate
    - gitlab-terraform plan

terraform_apply:
  stage: apply
  script:
    - gitlab-terraform apply -auto-approve

terraform_destroy:
  stage: destroy
  script:
    - gitlab-terraform destroy -auto-approve
  when: manual
