stages:
  - plan
  - apply
  - destroy

variables:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"

terraform_plan:
  stage: plan
  image:
    name: registry.gitlab.com/gitlab-org/terraform-images/releases/1.4:v1.0.0
    entrypoint: [""]
  script:
    - gitlab-terraform init
    - gitlab-terraform validate
    - gitlab-terraform plan

terraform_apply:
  stage: apply
  image:
    name: registry.gitlab.com/gitlab-org/terraform-images/releases/1.4:v1.0.0
    entrypoint: [""]
  script:
    - gitlab-terraform apply -auto-approve

terraform_destroy:
  stage: destroy
  image:
    name: registry.gitlab.com/gitlab-org/terraform-images/releases/1.4:v1.0.0
    entrypoint: [""]
  script:
    - gitlab-terraform destroy -auto-approve
  when: manual
