stages:
  - plan
  - apply
  - destroy

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

plan:
  image: hashicorp/terraform:latest
  script:
    - terraform init
    - terraform plan

apply:
  image: hashicorp/terraform:latest
  script:
    - terraform apply -auto-approve

destroy:
  script:
    - terraform destroy -auto-approve
  when: manual
