stages:
  - plan
  - apply
  - destroy

variables:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"

terraform_plan:
  stage: plan
  image: hashicorp/terraform:latest
  script:
    - cd terraform-gitlab-s3-bucket/
    - terraform --version
    - terraform init
    - terraform validate
    - terraform plan

terraform_apply:
  stage: apply
  image: hashicorp/terraform:latest
  script:
    - cd terraform-gitlab-s3-bucket/
    - terraform --version
    - terraform init
    - terraform apply -auto-approve

terraform_destroy:
  stage: destroy
  image: hashicorp/terraform:latest
  script:
    - cd terraform-gitlab-s3-bucket/
    - terraform --version
    - terraform init
    - terraform destroy -auto-approve
  when: manual
