# .gitlab-ci.yml
# file is working with a pre-defined template

include:
  - template: Terraform/Base.gitlab-ci.yml

variables:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"

stages:
  - validate
  - build
  - deploy
  - cleanup

validate:
  extends: .terraform:validate

build:
  extends: .terraform:build

deploy:
  extends: .terraform:deploy
  when: on_successful

cleanup:
  script:
    - gitlab-terraform destroy -auto-approve
  when: manual
